#!/usr/bin/env sh
. "$(dirname "$0")/h"

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

if [ -z "$COMMIT_MSG" ] || [ ${#COMMIT_MSG} -lt 10 ]; then
  echo "Error: Commit message is too short or empty!"
  exit 1
fi
